[build]
  # Direktori publish adalah direktori utama (root) dari proyek
  publish   = "."
  # Lokasi function kita
  functions = "chatbot/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]
