# Konfigurasi untuk proses build di Netlify
[build]
  # Memberi tahu Netlify bahwa semua file web (index.html, dll.) ada di dalam folder 'chatbot'
  publish   = "chatbot"
  # Lokasi folder functions Anda, sesuai dengan struktur di GitHub Anda
  functions = "chatbot/netlify/functions"

# Konfigurasi spesifik untuk serverless functions
[functions]
  # Menggunakan bundler esbuild yang cepat dan efisien
  node_bundler = "esbuild"
  # Baris 'external_node_modules' yang menyebabkan error telah dihapus.
  # Library Google AI sekarang akan disertakan dengan benar.

