[build]
publish = "chatbot"

[functions]
directory = "chatbot/netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["@google/generative-ai"]

[functions.environment]
GOOGLE_API_KEY = "$GOOGLE_API_KEY"
